title: Humble Theologian
tagline: Learning, loving and living the faith.
description: A personal theology and Bible study resource for Bible college students and serious theologically minded Christians.
author: Shayne Johnston
url: "https://humbletheologian.com"
baseurl: ""
permalink: /:categories/:title/
markdown: kramdown
theme: null

collections:
  love-as-a-verb:
    output: true
    permalink: /love-as-a-verb/:name/
  spurgeon:
    output: true
    permalink: /spurgeon/:name/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - CONTENT-GUIDE.md
  - GITHUB-PAGES-SETUP.md
